# to start "task generate"
version: "3"

tasks:
  generate:
    desc: "Generate code from proto files"
    aliases:
      - gen
    cmds:
      - protoc -I proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative proto/sso/sso.proto